# サイズの大きい文字列をチャンクに分けて書き込む

poem="sdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgssdfgsdfgsdfgsdfgfgsdgfsfgsdfgsdfgsdfgsdfgs"
fout =open('source/relativity','wt')
size=len(poem)
offset=0
chunk=100
while True:
    if offset>size:
        break;
    fout.write(poem[offset:offset+chunk])
    offset+=chunk
   
